var annotated_dup =
[
    [ "taixu", "namespacetaixu.html", [
      [ "editor", "namespacetaixu_1_1editor.html", [
        [ "Application", "classtaixu_1_1editor_1_1Application.html", "classtaixu_1_1editor_1_1Application" ],
        [ "IUIComponent", "classtaixu_1_1editor_1_1IUIComponent.html", "classtaixu_1_1editor_1_1IUIComponent" ],
        [ "ConsoleComponent", "classtaixu_1_1editor_1_1ConsoleComponent.html", "classtaixu_1_1editor_1_1ConsoleComponent" ],
        [ "DetailComponent", "classtaixu_1_1editor_1_1DetailComponent.html", "classtaixu_1_1editor_1_1DetailComponent" ],
        [ "FileComponent", "classtaixu_1_1editor_1_1FileComponent.html", "classtaixu_1_1editor_1_1FileComponent" ],
        [ "HierarchyComponent", "classtaixu_1_1editor_1_1HierarchyComponent.html", "classtaixu_1_1editor_1_1HierarchyComponent" ],
        [ "MenuComponent", "classtaixu_1_1editor_1_1MenuComponent.html", "classtaixu_1_1editor_1_1MenuComponent" ],
        [ "RenderComponent", "classtaixu_1_1editor_1_1RenderComponent.html", "classtaixu_1_1editor_1_1RenderComponent" ],
        [ "StatusBarComponent", "classtaixu_1_1editor_1_1StatusBarComponent.html", "classtaixu_1_1editor_1_1StatusBarComponent" ],
        [ "ToolbarComponent", "classtaixu_1_1editor_1_1ToolbarComponent.html", "classtaixu_1_1editor_1_1ToolbarComponent" ],
        [ "MainWindow", "classtaixu_1_1editor_1_1MainWindow.html", "classtaixu_1_1editor_1_1MainWindow" ],
        [ "MainWindowContext", "classtaixu_1_1editor_1_1MainWindowContext.html", "classtaixu_1_1editor_1_1MainWindowContext" ],
        [ "EditorStyle", "structtaixu_1_1editor_1_1EditorStyle.html", "structtaixu_1_1editor_1_1EditorStyle" ],
        [ "ImguiSurface", "classtaixu_1_1editor_1_1ImguiSurface.html", "classtaixu_1_1editor_1_1ImguiSurface" ]
      ] ],
      [ "Clock", "classtaixu_1_1Clock.html", "classtaixu_1_1Clock" ],
      [ "noncopyable", "classtaixu_1_1noncopyable.html", "classtaixu_1_1noncopyable" ],
      [ "IObserver", "classtaixu_1_1IObserver.html", "classtaixu_1_1IObserver" ],
      [ "ISubject", "classtaixu_1_1ISubject.html", "classtaixu_1_1ISubject" ],
      [ "PublicSingleton", "classtaixu_1_1PublicSingleton.html", "classtaixu_1_1PublicSingleton" ],
      [ "NotImplementedException", "classtaixu_1_1NotImplementedException.html", "classtaixu_1_1NotImplementedException" ],
      [ "Engine", "classtaixu_1_1Engine.html", "classtaixu_1_1Engine" ],
      [ "BufferElement", "structtaixu_1_1BufferElement.html", "structtaixu_1_1BufferElement" ],
      [ "BufferLayout", "classtaixu_1_1BufferLayout.html", "classtaixu_1_1BufferLayout" ],
      [ "Camera", "classtaixu_1_1Camera.html", "classtaixu_1_1Camera" ],
      [ "IElementBuffer", "classtaixu_1_1IElementBuffer.html", "classtaixu_1_1IElementBuffer" ],
      [ "IFrameBuffer", "classtaixu_1_1IFrameBuffer.html", "classtaixu_1_1IFrameBuffer" ],
      [ "Vertex", "structtaixu_1_1Vertex.html", "structtaixu_1_1Vertex" ],
      [ "Texture", "structtaixu_1_1Texture.html", "structtaixu_1_1Texture" ],
      [ "Mesh", "classtaixu_1_1Mesh.html", "classtaixu_1_1Mesh" ],
      [ "Model_Data", "classtaixu_1_1Model__Data.html", "classtaixu_1_1Model__Data" ],
      [ "IShader", "classtaixu_1_1IShader.html", "classtaixu_1_1IShader" ],
      [ "IShaderProgram", "classtaixu_1_1IShaderProgram.html", "classtaixu_1_1IShaderProgram" ],
      [ "ITexture", "classtaixu_1_1ITexture.html", "classtaixu_1_1ITexture" ],
      [ "IVertexArray", "classtaixu_1_1IVertexArray.html", "classtaixu_1_1IVertexArray" ],
      [ "IVertexBuffer", "classtaixu_1_1IVertexBuffer.html", "classtaixu_1_1IVertexBuffer" ],
      [ "Render_Data", "classtaixu_1_1Render__Data.html", "classtaixu_1_1Render__Data" ],
      [ "Render_Context", "classtaixu_1_1Render__Context.html", "classtaixu_1_1Render__Context" ],
      [ "Renderer", "classtaixu_1_1Renderer.html", "classtaixu_1_1Renderer" ],
      [ "TX_GLFWwindow", "classtaixu_1_1TX__GLFWwindow.html", "classtaixu_1_1TX__GLFWwindow" ],
      [ "IWindow", "classtaixu_1_1IWindow.html", "classtaixu_1_1IWindow" ],
      [ "IWindowContext", "classtaixu_1_1IWindowContext.html", "classtaixu_1_1IWindowContext" ],
      [ "OGLContext", "classtaixu_1_1OGLContext.html", "classtaixu_1_1OGLContext" ],
      [ "OGLElementBuffer", "classtaixu_1_1OGLElementBuffer.html", "classtaixu_1_1OGLElementBuffer" ],
      [ "OGLFrameBuffer", "classtaixu_1_1OGLFrameBuffer.html", "classtaixu_1_1OGLFrameBuffer" ],
      [ "OGLShader", "classtaixu_1_1OGLShader.html", "classtaixu_1_1OGLShader" ],
      [ "OGLShaderProgram", "classtaixu_1_1OGLShaderProgram.html", "classtaixu_1_1OGLShaderProgram" ],
      [ "OGLTexture", "classtaixu_1_1OGLTexture.html", "classtaixu_1_1OGLTexture" ],
      [ "OGLVertexArray", "classtaixu_1_1OGLVertexArray.html", "classtaixu_1_1OGLVertexArray" ],
      [ "OGLVertexBuffer", "classtaixu_1_1OGLVertexBuffer.html", "classtaixu_1_1OGLVertexBuffer" ],
      [ "GUID_Generator", "classtaixu_1_1GUID__Generator.html", null ],
      [ "Asset", "structtaixu_1_1Asset.html", "structtaixu_1_1Asset" ],
      [ "AssetManager", "classtaixu_1_1AssetManager.html", "classtaixu_1_1AssetManager" ],
      [ "IJsonable", "classtaixu_1_1IJsonable.html", "classtaixu_1_1IJsonable" ],
      [ "Project", "structtaixu_1_1Project.html", "structtaixu_1_1Project" ],
      [ "ProjectManager", "classtaixu_1_1ProjectManager.html", "classtaixu_1_1ProjectManager" ]
    ] ]
];