var annotated_dup =
[
    [ "taixu", "namespacetaixu.html", [
      [ "editor", "namespacetaixu_1_1editor.html", [
        [ "Application", "classtaixu_1_1editor_1_1Application.html", "classtaixu_1_1editor_1_1Application" ],
        [ "ApplicationContext", "structtaixu_1_1editor_1_1ApplicationContext.html", "structtaixu_1_1editor_1_1ApplicationContext" ],
        [ "IUIComponent", "classtaixu_1_1editor_1_1IUIComponent.html", "classtaixu_1_1editor_1_1IUIComponent" ],
        [ "ConsoleComponent", "classtaixu_1_1editor_1_1ConsoleComponent.html", "classtaixu_1_1editor_1_1ConsoleComponent" ],
        [ "DetailComponent", "classtaixu_1_1editor_1_1DetailComponent.html", "classtaixu_1_1editor_1_1DetailComponent" ],
        [ "FileComponent", "classtaixu_1_1editor_1_1FileComponent.html", "classtaixu_1_1editor_1_1FileComponent" ],
        [ "HierarchyComponent", "classtaixu_1_1editor_1_1HierarchyComponent.html", "classtaixu_1_1editor_1_1HierarchyComponent" ],
        [ "MenuComponent", "classtaixu_1_1editor_1_1MenuComponent.html", "classtaixu_1_1editor_1_1MenuComponent" ],
        [ "RenderComponent", "classtaixu_1_1editor_1_1RenderComponent.html", "classtaixu_1_1editor_1_1RenderComponent" ],
        [ "ToolbarComponent", "classtaixu_1_1editor_1_1ToolbarComponent.html", "classtaixu_1_1editor_1_1ToolbarComponent" ],
        [ "ImguiSurface", "classtaixu_1_1editor_1_1ImguiSurface.html", "classtaixu_1_1editor_1_1ImguiSurface" ],
        [ "MainWindow", "classtaixu_1_1editor_1_1MainWindow.html", "classtaixu_1_1editor_1_1MainWindow" ],
        [ "MainWindowContext", "structtaixu_1_1editor_1_1MainWindowContext.html", "structtaixu_1_1editor_1_1MainWindowContext" ],
        [ "EditorStyle", "structtaixu_1_1editor_1_1EditorStyle.html", "structtaixu_1_1editor_1_1EditorStyle" ]
      ] ],
      [ "noncopyable", "classtaixu_1_1noncopyable.html", "classtaixu_1_1noncopyable" ],
      [ "PublicSingleton", "classtaixu_1_1PublicSingleton.html", "classtaixu_1_1PublicSingleton" ],
      [ "Camera", "classtaixu_1_1Camera.html", "classtaixu_1_1Camera" ],
      [ "IElementBuffer", "classtaixu_1_1IElementBuffer.html", null ],
      [ "Vertex", "structtaixu_1_1Vertex.html", "structtaixu_1_1Vertex" ],
      [ "Texture", "structtaixu_1_1Texture.html", "structtaixu_1_1Texture" ],
      [ "Mesh", "classtaixu_1_1Mesh.html", "classtaixu_1_1Mesh" ],
      [ "Model", "classtaixu_1_1Model.html", "classtaixu_1_1Model" ],
      [ "IShader", "classtaixu_1_1IShader.html", "classtaixu_1_1IShader" ],
      [ "IShaderProgram", "classtaixu_1_1IShaderProgram.html", "classtaixu_1_1IShaderProgram" ],
      [ "ITexture", "classtaixu_1_1ITexture.html", "classtaixu_1_1ITexture" ],
      [ "IVertexArray", "classtaixu_1_1IVertexArray.html", "classtaixu_1_1IVertexArray" ],
      [ "IVertexBuffer", "classtaixu_1_1IVertexBuffer.html", null ],
      [ "Render_Data", "classtaixu_1_1Render__Data.html", "classtaixu_1_1Render__Data" ],
      [ "Render_Context", "classtaixu_1_1Render__Context.html", "classtaixu_1_1Render__Context" ],
      [ "Renderer", "classtaixu_1_1Renderer.html", "classtaixu_1_1Renderer" ],
      [ "TX_GLFWwindow", "classtaixu_1_1TX__GLFWwindow.html", "classtaixu_1_1TX__GLFWwindow" ],
      [ "IWindow", "classtaixu_1_1IWindow.html", "classtaixu_1_1IWindow" ],
      [ "IWindowContext", "structtaixu_1_1IWindowContext.html", "structtaixu_1_1IWindowContext" ],
      [ "OGLShader", "classtaixu_1_1OGLShader.html", "classtaixu_1_1OGLShader" ],
      [ "OGLShaderProgram", "classtaixu_1_1OGLShaderProgram.html", "classtaixu_1_1OGLShaderProgram" ],
      [ "OGLTexture", "classtaixu_1_1OGLTexture.html", "classtaixu_1_1OGLTexture" ],
      [ "OGLVertexArray", "classtaixu_1_1OGLVertexArray.html", "classtaixu_1_1OGLVertexArray" ],
      [ "GUID_Generator", "classtaixu_1_1GUID__Generator.html", null ],
      [ "Asset", "structtaixu_1_1Asset.html", "structtaixu_1_1Asset" ],
      [ "Asset_Manager", "classtaixu_1_1Asset__Manager.html", "classtaixu_1_1Asset__Manager" ],
      [ "IJsonable", "classtaixu_1_1IJsonable.html", "classtaixu_1_1IJsonable" ],
      [ "Project", "structtaixu_1_1Project.html", null ],
      [ "ProjectManager", "classtaixu_1_1ProjectManager.html", null ]
    ] ]
];