//
// Created by xmmmmmovo on 2023/5/2.
//

#ifndef ENGINE_RUNTIME_MANAGEMENT_ECS_SYSTEM_EVENT_HPP
#define ENGINE_RUNTIME_MANAGEMENT_ECS_SYSTEM_EVENT_HPP

namespace taixu {}

#endif//ENGINE_RUNTIME_MANAGEMENT_ECS_SYSTEM_EVENT_HPP
