//
// Created by xmmmmmovo on 2023/5/21.
//

#ifndef ENGINE_RUNTIME_MANAGEMENT_ECS_COMPONENTS_LIGHT_LIGHT_SOURCE_TYPE_HPP
#define ENGINE_RUNTIME_MANAGEMENT_ECS_COMPONENTS_LIGHT_LIGHT_SOURCE_TYPE_HPP

namespace taixu {

enum class LightSourseType { POINT, INVALID };

}

#endif//ENGINE_RUNTIME_MANAGEMENT_ECS_COMPONENTS_LIGHT_LIGHT_SOURCE_TYPE_HPP
