//
// Created by xmmmmmovo on 1/5/2024.
//

#ifndef ENGINE_SRC_RUNTIME_PLATFORM_OS_WINDOWS_WINDOWS_HEADERS_86DE43020A8F4A61922DC862C427D072
#define ENGINE_SRC_RUNTIME_PLATFORM_OS_WINDOWS_WINDOWS_HEADERS_86DE43020A8F4A61922DC862C427D072

#define NOGDICAPMASKS
#define NOVIRTUALKEYCODES
#define NOWINSTYLES
#define NOSYSMETRICS
#define NOMENUS
#define NOICONS
#define NOKEYSTATES
#define NOSYSCOMMANDS
#define NORASTEROPS
#define NOSHOWWINDOW
#define OEMRESOURCE
#define NOATOM
#define NOCLIPBOARD
#define NOCOLOR
#define NOCTLMGR
#define NODRAWTEXT
#define NOGDI
#define NOKERNEL
#define NOUSER
// #define NONLS
#define NOMB
#define NOMEMMGR
#define NOMETAFILE
#define NOMINMAX
#define NOMSG
#define NOOPENFILE
#define NOSCROLL
#define NOSERVICE
#include <Windows.h>

#endif// ENGINE_SRC_RUNTIME_PLATFORM_OS_WINDOWS_WINDOWS_HEADERS_86DE43020A8F4A61922DC862C427D072
