//
// Created by xmmmmmovo on 1/5/2024.
//

#ifndef ENGINE_SRC_RUNTIME_PLATFORM_OS_WINDOWS_WINDOWS_MIN_72E94667A0E34E84AF13C7D15768C2A0
#define ENGINE_SRC_RUNTIME_PLATFORM_OS_WINDOWS_WINDOWS_MIN_72E94667A0E34E84AF13C7D15768C2A0

#define NOGDICAPMASKS
#define NOVIRTUALKEYCODES
#define NOWINSTYLES
#define NOSYSMETRICS
#define NOMENUS
#define NOICONS
#define NOKEYSTATES
#define NOSYSCOMMANDS
#define NORASTEROPS
#define NOSHOWWINDOW
#define OEMRESOURCE
#define NOATOM
#define NOCLIPBOARD
#define NOCOLOR
#define NOCTLMGR
#define NODRAWTEXT
#define NOGDI
#define NOKERNEL
#define NOUSER
// #define NONLS
#define NOMB
#define NOMEMMGR
#define NOMETAFILE
#define NOMSG
#define NOOPENFILE
#define NOSCROLL
#define NOSERVICE

#define NOMINMAX

#include <windows.h>

#endif// ENGINE_SRC_RUNTIME_PLATFORM_OS_WINDOWS_WINDOWS_MIN_72E94667A0E34E84AF13C7D15768C2A0
