//
// Created by xmmmmmovo on 2023/2/26.
//

#include "json_parser.hpp"

namespace taixu {
//template<typename T>
//std::string dumpJsonString(T const& jsonObj) {}
//std::string dumpJsonFile(std::ifstream const& stream) {}

//template<typename I, typename T>
//I loadJsonString(std::string jsonStr) {}
//template<typename I, typename T>
//I loadJsonFile(std::ofstream const& stream) {}
}// namespace taixu