//
// Created by xmmmmmovo on 20/09/2023.
//

#ifndef ENGINE_SRC_RUNTIME_MANAGEMENT_GRAPHICS_RHI_TX_DEVIECE_HPP
#define ENGINE_SRC_RUNTIME_MANAGEMENT_GRAPHICS_RHI_TX_DEVIECE_HPP

namespace taixu {

class IDevice {};

}// namespace taixu

#endif// ENGINE_SRC_RUNTIME_MANAGEMENT_GRAPHICS_RHI_TX_DEVIECE_HPP
