set(TARGET_IMGUIINI_FILE ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/imgui.ini)
set(TARGET_ASSETS_DIR ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/assets)
set(TARGET_RES_DIR ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/res)

set(IMGUIINI_FILE ${ENGINE_ROOT_DIR}/editor/imgui.ini)
set(ASSETS_DIR ${ENGINE_ROOT_DIR}/assets)
set(RES_DIR ${ENGINE_ROOT_DIR}/editor/res)

message("copy start")

if ((NOT EXISTS ${TARGET_IMGUIINI_FILE}) OR (${IMGUIINI_FILE} IS_NEWER_THAN ${TARGET_IMGUIINI_FILE}))
    message("Move imgui.ini...")
    file(COPY ${IMGUIINI_FILE} DESTINATION ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
endif ()

if ((NOT EXISTS ${TARGET_ASSETS_DIR}) OR (${ASSETS_DIR} IS_NEWER_THAN ${TARGET_ASSETS_DIR}))
    message("Move assets dir...")
    file(COPY ${ASSETS_DIR} DESTINATION ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
endif ()

if ((NOT EXISTS ${TARGET_RES_DIR}) OR (${RES_DIR} IS_NEWER_THAN ${TARGET_RES_DIR}))
    message("Move res dir...")
    file(COPY ${RES_DIR} DESTINATION ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
endif ()