if ((NOT EXISTS ${DEST_PATH}) OR (${SRC_PATH} IS_NEWER_THAN ${DEST_PATH}))
    message("Move to ${DEST_PATH}...")
    file(COPY ${SRC_PATH} DESTINATION ${DEST_PATH})
else ()
    message("${SRC_PATH} is not newer than dest")
endif ()